name: Docker image for songServer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: build and publish the image
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: docker build . --file Dockerfile --tag songsserver:$(date +%s)
