# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: build and publish the image
        with:
          node-version: 20
          build-args: "MONGO_URL=${{ secrets.MONGO_URL }}"
      - run: |
          docker login --username Menigedegna --password ${{secrets.GHCR}}
          docker build -t ghcr.io/menigedegna/songsserver:latest .
          docker push ghcr.io/menigedegna/songsserver:latest
