# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Docker image for songServer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: build and publish the image
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
      - run: docker build . --file Dockerfile --tag songsserver:latest
